---
title: "Rapp et. al Time Series Analysis and Forecasting"
output: html_document
date: "2025-05-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Extract proportion of ideal tapping days from Rapp et. al locations

```{r, message=FALSE, warning=FALSE, fig.height=10, fig.width=12}
library(terra)
library(tidyverse)
library(sf)

# Read in file
sap_day_prop <- rast("../Data_Clean/sap_day_prop.tif")

# Create vect of lats and lons
# Leaving out Quebec because we only have US PRISM
lats <- c(37.011, 38.231, 41.625, 42.532, 43.734)
lons <- c(-82.676, -79.658, -87.081, -72.190, -72.249)
locations <- terra::vect(data.frame(lon = lons, lat = lats))

# Extract proportions at those locations
rapp_props <- terra::extract(sap_day_prop, locations)
colnames(rapp_props)[-1] <- 1991:2020

# Prepare dataframe for plotting
sites <- c("Divide Ridge", "Southernmost Maple",
           "Indiana Dunes National Lakeshore", "Harvard Forest",
           "Dartmouth Organic Farm")
rapp_props[, 1] <- sites
colnames(rapp_props)[1] <- "Site"
rapp_props_long <- rapp_props |>
  pivot_longer(-Site, names_to = "Year", values_to = "Mean") |>
  mutate(Year = as.integer(Year))

# Plot
ggplot(rapp_props_long, aes(Year, Mean, col = Site, group = Site)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  scale_color_viridis_d() +
  scale_x_continuous(breaks = seq(1990, 2020, by = 2)) +
  scale_y_continuous("Proportion", breaks = seq(0.1, 0.6, by = 0.1), limits = c(0.1, 0.6)) +
  ggtitle("Proportion of Ideal Maple Syrup Tapping Days for Rapp et. al Locations") +
  theme(plot.title = element_text(hjust = 0.5))
```

## Time series analysis

```{r, warning=FALSE}
library(trend)

sens.slope(rapp_props_long$Mean[rapp_props_long$Site == "Divide Ridge"])
sens.slope(rapp_props_long$Mean[rapp_props_long$Site == "Southernmost Maple"])
sens.slope(rapp_props_long$Mean[rapp_props_long$Site == "Indiana Dunes National Lakeshore"])
sens.slope(rapp_props_long$Mean[rapp_props_long$Site == "Harvard Forest"])
sens.slope(rapp_props_long$Mean[rapp_props_long$Site == "Dartmouth Organic Farm"])
```

Divide Ridge seems to the only farm where we have evidence of a negative trend
over time.

### Divide Ridge time series analysis

```{r}
# Make dataframe for just Divide Ridge
rapp_divide <- rapp_props_long |>
  filter(Site == "Divide Ridge") |>
  select(-Site)

# Plot just Divide Ridge
ggplot(rapp_divide, aes(Year, Mean, group = 1)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  scale_x_continuous(breaks = seq(1990, 2020, by = 2)) +
  scale_y_continuous("Proportion", breaks = seq(0.15, 0.4, by = 0.05), limits = c(0.14, 0.4)) +
  ggtitle("Proportion of Ideal Maple Syrup Tapping Days for Divide Ridge") +
  theme(plot.title = element_text(hjust = 0.5))

# Make lm
divide_lm <- lm(Mean ~ Year, data = rapp_divide)
summary(divide_lm)

# Make the data stationary
rapp_divide <- rapp_divide |>
  mutate(logMean = log(Mean))
divide_log_lm <- lm(logMean ~ Year, data = rapp_divide)
divide_log_lm_df <- data.frame(Year = rapp_divide$Year, Residuals = divide_log_lm$residuals)

# Plot stationary data
ggplot(divide_log_lm_df, aes(Year, Residuals, group = 1)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  scale_x_continuous(breaks = seq(1990, 2020, by = 2)) +
  scale_y_continuous(breaks = round(seq(-0.6, 0.4, by = 0.2), 1), limits = c(-0.6, 0.4)) +
  ggtitle("Residuals of Stationary Data") +
  theme(plot.title = element_text(hjust = 0.5))

# Test for independence
divide_residuals_ts <- ts(divide_log_lm$residuals)
acf(divide_residuals_ts, lag.max = 12)
pacf(divide_residuals_ts, lag.max = 12)
Box.test(divide_residuals_ts, lag = 6, type = "Ljung")
Box.test(divide_residuals_ts, lag = 12, type = "Ljung")
```

There is not enough evidence to suggest autocorrelation.

```{r, message=FALSE, warning=FALSE}
library(forecast)
library(lmtest)

# Fit ARIMA model
divide_ts <- ts(rapp_divide$logMean)
divide_arima <- Arima(divide_ts, order = c(4, 0, 0))
summary(divide_arima)
checkresiduals(divide_arima)

# Add 90% confidence interval to current data
current <- data.frame(fit = as.numeric(divide_arima$fitted),
                      lower = as.numeric(divide_arima$fitted -
                                           1.64 * sqrt(divide_arima$sigma2)),
                      upper = as.numeric(divide_arima$fitted +
                                           1.64 * sqrt(divide_arima$sigma2)),
                      Year = rapp_divide$Year)

# Forecast and add 90% confidence interval
ahead <- forecast(divide_arima, h = 10, level = 90)
ahead <- data.frame(fit = as.numeric(ahead$mean),
                    lower = as.numeric(ahead$lower[, 1]),
                    upper = as.numeric(ahead$upper[, 1]),
                    Year = 2021:2030)

# Combine into one data frame
final <- rbind(current, ahead)

# Plot original and prediction
ggplot(final) +
  geom_line(aes(Year, fit, group = 1, color = "Forecast"), lwd = 1) +
  geom_line(aes(Year, lower, group = 1, color = "Lower CL (90%)"), lty = 2) +
  geom_line(aes(Year, upper, group = 1, color = "Upper CL (90%)"), lty = 2) +
  geom_line(data = rapp_divide, mapping = aes(Year, logMean, group = 1, color = "Observed"), lwd = 1) +
  theme_bw() +
  scale_y_continuous("Log Proportion", breaks = seq(-2, -0.5, by = 0.5), limits = c(-2, -0.5)) +
  scale_color_manual(values = c("red", "blue", "black", "black"),
                     breaks = c("Observed", "Forecast", "Upper CL (90%)", "Lower CL (90%)")) +
  labs(color = "") +
  ggtitle("Model Fit: ARIMA(4, 0, 0)") +
  theme(plot.title = element_text(hjust = 0.5))
```
