---
title: "Validation"
output: html_document
date: "2025-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Do my plots from raster_prism_practice_3.R make sense?

```{r, message=FALSE, warning=FALSE}
library(terra)
library(tidyverse)
library(sf)

# Read in file
sap_day_prop <- rast("../Data_Clean/sap_day_prop.tif")

# Plot first year (2020)
us_states <- read_sf("../Data_Clean/US_State_Lines/cb_2018_us_state_500k.shp")
plot(sap_day_prop[[30]])
title(main = "Proportion of Ideal Maple Syrup Tapping Days, Jan-Apr 2020")
lines(us_states)
```

### Bryce Canyon City, Utah

[Wikipedia](https://en.wikipedia.org/wiki/Bryce_Canyon_City,_Utah)

```{r}
bryce_canyon <- terra::vect(data.frame(lon = -112.156944, lat = 37.673889))
terra::extract(sap_day_prop[[30]], bryce_canyon)
```

Looking online, this proportion looks generally correct, as Bryce Canyon is one
of the colder parts of Utah.

[Visit Utah](https://www.visitutah.com/places-to-go/parks-outdoors/bryce-canyon/winter-in-bryce-canyon#:~:text=Winter%20Weather%20in%20Bryce%20Canyon&text=Normally%2C%20winter%20daytime%20highs%20are,occur%20during%20any%20winter%20month.)

"Expect freezing temperatures most nights from October through May, with the possibility of snow."

### Fresh Air Fund Maple Farm

[Information about the farm](https://www.maplesyrupfarms.org/NYse.php)

[Located in Fishkill, NY](https://en.wikipedia.org/wiki/Fishkill,_New_York)

```{r}
fresh_air <- terra::vect(data.frame(lon = -73.899167, lat = 41.534167))
terra::extract(sap_day_prop[[30]], fresh_air)
```

Extract this proportion over time:

```{r}
fresh_air_props <- terra::extract(sap_day_prop, fresh_air)
colnames(fresh_air_props)[-1] <- 1991:2020

fresh_air_props_df <- select(fresh_air_props, -1) |>
  pivot_longer(everything(), names_to = "Year", values_to = "Mean") |>
  mutate(Year = as.numeric(Year))

ggplot(fresh_air_props_df, aes(Year, Mean, group = 1)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(1991, 2020, by = 2)) +
  scale_y_continuous(breaks = seq(0.2, 0.5, by = 0.1), limits = c(0.2, 0.5)) +
  ylab("Proportion") +
  ggtitle("Proportion of Ideal Maple Syrup Tapping Days for Fresh Air Fund Maple Farm") +
  theme_bw()
```
