// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sap_day_rast_helper
double sap_day_rast_helper(NumericVector cell_vect);
RcppExport SEXP _terra_practice_sap_day_rast_helper(SEXP cell_vectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_vect(cell_vectSEXP);
    rcpp_result_gen = Rcpp::wrap(sap_day_rast_helper(cell_vect));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terra_practice_sap_day_rast_helper", (DL_FUNC) &_terra_practice_sap_day_rast_helper, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_terra_practice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
