// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sap_day_rast_helper
NumericVector sap_day_rast_helper(NumericMatrix tmax_vals, NumericMatrix tmin_vals);
RcppExport SEXP _terra_practice_sap_day_rast_helper(SEXP tmax_valsSEXP, SEXP tmin_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tmax_vals(tmax_valsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tmin_vals(tmin_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(sap_day_rast_helper(tmax_vals, tmin_vals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terra_practice_sap_day_rast_helper", (DL_FUNC) &_terra_practice_sap_day_rast_helper, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_terra_practice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
